'<%= ENV['RAILS_ENV'] %>':
  adapter: postgresql
  encoding: unicode
  database: rails_deployment_example_<%= ENV['RAILS_ENV'] %>
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>